### PR TITLE
Explicitly cast boolean and number values in signature base string

### PR DESCRIPTION
**Pull request by okcoker**
So I just ran into #9 myself. I think @jmendiara has it a little mixed up in [his example](https://github.com/bettiolo/oauth-signature-js/pull/9#issuecomment-56977954). Because of [this line](https://github.com/bettiolo/oauth-signature-js/blob/fab13230d9b068d68ab946ca926472fc11f11180/src/app/oauth-signature.js#L185), if you were to generate a signature with parameters such as the following:

```js
var params = {
     from: 0,
     another: false,
     to: 1
};
```
The signature base string would include something like: `http://foo.com/bar?from=&another=&to=1` instead of `http://foo.com/bar?from=0&another=false&to=1`.

Without this, the user of the library would have to be mindful in always converting parameter values to strings. I also added tests so this fixes #9.

Any plans on upgrading `uri-js` for #34 #35 #38?

### CODE REVIEW

**Comment by bettiolo** [comment]
Makes sense, thanks for implementing the tests.

**Comment by bettiolo** [comment]
Release the updated npm package.

**Comment by okcoker** [comment]
Thanks for the quick turnaround!

**Comment by bettiolo** [comment]
Your PR was awesome, thanks for the effort and for updating the tests

**Pull request merged**
